### ISSUE TITLE
Страница статей

### ISSUE THREAD

**Issue by KonstantinKudelko** [KonstantinKudelko/church-website#71]
Задача сделать прототип страницы статей. Можно оформить в виде карточек, как это отрисовано в [Фигме.](https://www.figma.com/file/3Dd5fJut7C3K5s6k9MHQWG/Gospel-House-platform?type=design&node-id=0-1&mode=design&t=zzyTuW15qa1GPmt5-0)

![image](https://github.com/KonstantinKudelko/church-website/assets/16194085/7cbbd0db-afa0-4b14-a1c5-421c68ca597a)

Нижние теги можно опустить, а цвета для обложек положить в метаданные каждой статьи (файл `.mdx`).

**Comment by alinaguseva1997** [comment]
Я добавила переменные в статьи, но так и не смогла понять, как их использовать в компоненте при отрисовке.

**Comment by alinaguseva1997** [comment]
@KonstantinKudelko как использовать переменную с цветом при отрисовке статей? Мы же достаем всё из стейта с помощью map, а переменная с цветом сидит локально в каждой статье. В стилях тоже нельзя так подтянуть переменную.

**Comment by pavelliolia** [comment]
Я начал делать эту ишью в пятницу в бранче pavelliolia/add-articles-list-ui
